### ISSUE TITLE
1 inch margin

### ISSUE THREAD

**Issue by michaelaye** [MosesAstro/LaTeX_Templates#2]
Apparently, the 1 inch margin for the abstract is not correctly done (anymore?) ? I just printed out the PDF freshly compiled by OSX Tex Live using pdflatex, and it does have quite less than 1 inch margin, which seems to be the page setup of the Word template.

**Comment by MosesAstro** [comment]
Yes. I'm about to upload a fixed version. There were several aspects that were not compliant with the template released by LPI.

**Comment by michaelaye** [comment]
I played around and found that **ALL** geometry (not the figure related ones) commands can be replaced by simply `\usepackage[margin=1in]{geometry}`

**Comment by michaelaye** [comment]
The Bibliography section also has this un-sightly inset that costs space and that the Word template has not. But I don't see a simple way to remove it. :(

**Comment by MosesAstro** [comment]
Agreed. Working on that at the moment. It has to do with which type of section is being used and with the bst file used. Ross Beyer has an update, but I'm not a huge fan of it because it is too verbose.

**Comment by michaelaye** [comment]
Thanks! It seems, bst files are so much more complex than .sty files so I can't help at all. I think my .sty file is getting there.

**Comment by MosesAstro** [comment]
I've made some improvements. Let me know if you think this fixes your issue. I had to copy the bibliography environment from the class file and add it to the style file so I could make some modifications to the environment to get rid of that horrible indentation.

**Comment by michaelaye** [comment]
I'm confused, I don't see any changes from you apart from deleting the synctex and bbl file? Did you forget to push?

**Comment by MosesAstro** [comment]
Yes, I did.

The changes are committed now.

**Comment by MosesAstro** [comment]
Unfortunately, I'm not yet entirely familiar with github (I use this about once a year when I make changes to these templates)... I'm not sure if I lost some of your committed changes.

**Comment by MosesAstro** [comment]
This has been fixed. Still trying to decide whether moving away from individual margin settings in the style file to \usepackage[margin=1in]{geometry} in the template.tex is the best course of action. I can't come up with technical arguments for or against, so it seems like it would be clearer to the user to set the margins in the template .tex file.

**Comment by michaelaye** [comment]
There's a technical argument: The LPSC template rule is 1 inch everywhere, so more control, or setting each margin separately is superfluous. Plus, internally, `geometry` is just doing the same.
There's also a social argument: Less scary looking LaTex commands are increasing the likelihood of being used. ;) Thanks for your fixes!

**Comment by MosesAstro** [comment]
Agreed. Fixed. Well, commented out geometry in style file and added \usepackage[margin=1.0in]{geometry} to template file.

**Comment by michaelaye** [comment]
as you were saying that you are not yet very familiar with github: It is common to mention the issue number in the commit string so that github automatically links to the changes that fix a certain issue. So, in this case you would have mentioned something like "fixes #2" at the end of the commit comment.
